joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

servobot_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5

  constraints:
    goal_time: &goal_time_constraint 5
    stopped_velocity_tolerance: 0.004
    joint0:
      goal: 0.01
      trajectory: 0.08
    joint1:
      goal: 0.01
      trajectory: 0.08
    joint2:
      goal: 0.01
      trajectory: 0.08
    joint3:
      goal: 0.01
      trajectory: 0.08
    joint4:
      goal: 0.01
      trajectory: 0.08
    joint5:
      goal: 0.01
      trajectory: 0.08

  gains: # Required because we're controlling a velocity interface
    # joint0: {p: 0.08, i: 0.05, d: 0.15, i_clamp: 1}
    # joint1: {p: 0.08, i: 0.05, d: 0.15, i_clamp: 1}
    # joint2: {p: 0.08, i: 0.05, d: 0.14, i_clamp: 1}
    # joint3: {p: 0.08, i: 0.05, d: 0.12, i_clamp: 1}
    joint0: {p: 1, i: 0.1, d: 0.01, i_clamp: 1}
    joint1: {p: 1, i: 0.1, d: 0.01, i_clamp: 1}
    joint2: {p: 1, i: 0.1, d: 0.01, i_clamp: 1}   #1 0.04 0.12
    joint3: {p: 1, i: 0.1, d: 0.01, i_clamp: 1}   
    joint4: {p: 1, i: 0.1, d: 0.01, i_clamp: 1}   
    joint5: {p: 1, i: 0.1, d: 0.01, i_clamp: 1}   
    #so now positioncontroll seems don't need this section(gains)